app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'web'], function () {
    Route::auth();
    Route::get('Area', function () {
        Area::get();
    });
    Route::resource('areas', 'AreaController');
    Route::resource('districts', 'DistrictController');
    Route::resource('profile', 'ProfileController');
    Route::get('/', 'DistrictController@index');
    Route::get('district/0', 'DistrictController@index');
    Route::get('district/{district_id}', 'AreaController@district');
});

app/Map.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Map
 * @package App
 */
class Map extends Model
{
    /**
     * List of database fields that should not be edited
     *
     * @var array
     */
    protected $guarded = [
        'id', 'user_id'
    ];

    /**
     * Get all of the land (Area and District) models.
     */
    public function ownable()
    {
        return $this->morphTo();
    }
}

app/Http/Controllers/MapController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

/**
 * Class Map
 * @package App\Http\Controllers
 */
class Map extends Controller
{
    //
}

resources/views/map/index.blade.php
@extends('layouts.template')

@section('content')
    <style>
        th {
            text-align: center;
        }
    </style>
    <h1>Your Squaretown</h1>
    <a href="{{url('/areas/create')}}" class="btn btn-success">Create Area</a>
    <hr>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Name</th>
            <th>Type</th>
            <th>District</th>
            <th>Location</th>
            <th>Thumbs</th>
            <th colspan="3">Actions</th>
        </tr>
        </thead>
        <tbody>
        @unless (empty($areas))
            @foreach ($areas as $area)
                <tr align="center">
                    <td>{{ $area->name }}</td>
                    <td>{{ \App\Area::TYPES[$area->type] }}</td>
                    <td>{{ $area->district_id }}</td>
                    <td>{{ $area->grid_x }}:{{ $area->grid_y }}</td>
                    <td><img src="{{asset('img/area/'.$area->type.'.png')}}" height="35" width="30"></td>
                    <td><a href="{{url('areas',$area->id)}}" class="btn btn-primary">Visit</a></td>
                    <td><a href="{{route('areas.edit',$area->id)}}" class="btn btn-warning">Update</a></td>
                    <td>
                        {!! Form::open(['method' => 'DELETE', 'route'=>['areas.destroy', $area->id]]) !!}
                        {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
        @endunless


        </tbody>

    </table>
@endsection